import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Imagefooter from "@/components/Imagefooter";
import { Topbar } from "@/components/navbar";
import { Middle } from "@/components/navbar";
import { BottomNav } from "@/components/navbar";
import { Suspense } from "react";
import { LoadingSpinner } from "@/components/loadingSpinner";
import ErrorBoundary from "@/components/errorBoundary";

export const metadata = {
  title: "NITP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Topbar />
        <div className="sticky top-0 bg-white shadow-md z-[100]">
          <Middle />
          <BottomNav />
        </div>
        <ErrorBoundary >
          <Suspense fallback={<>Loading...</>} />
          {children}
          <Suspense />
        </ErrorBoundary>
        <Imagefooter />
        <Footer />
      </body>
    </html>
  );
}
