import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { Topbar } from "@/components/navbar";
import { Middle } from "@/components/navbar";
import { BottomNav } from "@/components/navbar";
import { Suspense } from "react";
import { LoadingSpinner } from "@/components/loadingSpinner";
import ErrorBoundary from "@/components/errorBoundary";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NITP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Topbar />
        <div className="sticky top-0 bg-white shadow-md z-[100]">
          <Middle />
          <BottomNav />
        </div>
        <ErrorBoundary >
        <Suspense fallback={<>Loading...</>} />
        {children}
        <Suspense />
        </ErrorBoundary>
        <Footer />
      </body>
    </html>
  );
}
